from __future__ import annotations

import os
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parents[2]
FRONTEND_DIR = ROOT_DIR / "frontend"
ASSETS_DIR = FRONTEND_DIR / "assets"
DB_PATH = ROOT_DIR / "backend" / "players.db"
BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "")

MAX_OFFLINE_PROGRESS_SECONDS = 8.0
MAX_KILLS_PER_TICK = 100
HERO_UNLOCK_COST = 0

STAGE_KILL_TARGETS = {
    "normal": 8,
    "group": 5,
    "elite": 3,
    "boss": 1,
}

WAVE_SIZE_MIN = 5
WAVE_SIZE_MAX = 10

WAVE_ARCHETYPES = [{'id': 'embers',
  'location': 'Сухой сай',
  'hint': 'Трава тут сухая. Любая искра быстро превращается в беду.',
  'slang': 'Тут степь сухая — искра мигом делает шум.',
  'signals': ['сухая трава', 'искры', 'жар'],
  'enemy_tags': ['wolf', 'spirit', 'totem', 'jackal'],
  'elite_tags': ['elite_wolf', 'elite_totem', 'elite_howler'],
  'boss_tags': ['boss_pyre', 'boss_wolf', 'boss_drought'],
  'modifiers': {'burn_mult': 1.24, 'tap_mult': 1.06, 'enemy_hp_mult': 0.98, 'enemy_attack_mult': 1.08}},
 {'id': 'stone',
  'location': 'Курганный пролом',
  'hint': 'Много панциря и тяжёлой кости. В лоб тут не шьют.',
  'slang': 'Тут жир в броне ходит. Просто так не пробьёшь.',
  'signals': ['панцирь', 'камень', 'тяжесть'],
  'enemy_tags': ['totem', 'wolf', 'yak'],
  'elite_tags': ['elite_totem', 'elite_rift', 'elite_bull'],
  'boss_tags': ['boss_idol', 'boss_guard', 'boss_stonehide'],
  'modifiers': {'enemy_armor_mult': 1.28, 'earth_pair_mult': 1.16, 'tap_mult': 0.9, 'dps_mult': 0.94}},
 {'id': 'storm',
  'location': 'Ветровой прогон',
  'hint': 'Шустрые твари и рваный темп. Тут важен рисунок боя.',
  'slang': 'Тут всё бегает, крутится и не стоит ровно.',
  'signals': ['вихрь', 'рывки', 'следы в воздухе'],
  'enemy_tags': ['raven', 'spirit', 'wolf', 'moth'],
  'elite_tags': ['elite_wolf', 'elite_spirit', 'elite_raven'],
  'boss_tags': ['boss_wind', 'boss_mirror'],
  'modifiers': {'swipe_mult': 1.18,
                'air_pair_mult': 1.12,
                'enemy_attack_interval_mult': 0.9,
                'enemy_attack_mult': 1.05}},
 {'id': 'tide',
  'location': 'Сырая низина',
  'hint': 'Воздух тяжёлый, земля липнет. Долгий нажим тут не зря придумали.',
  'slang': 'Тут не спешат. Кто умеет держать поток — тот и давит.',
  'signals': ['сырость', 'вязь', 'тягучий след'],
  'enemy_tags': ['spirit', 'totem', 'mireling'],
  'elite_tags': ['elite_spirit', 'elite_rift', 'elite_mire'],
  'boss_tags': ['boss_void', 'boss_tidekeeper', 'boss_marsh'],
  'modifiers': {'hold_mult': 1.22, 'water_pair_mult': 1.12, 'burn_mult': 0.86, 'enemy_attack_interval_mult': 1.08}},
 {'id': 'ritual',
  'location': 'Шаманский круг',
  'hint': 'Место злое и хитрое. Простая долбёжка тут быстро тухнет.',
  'slang': 'Круг шепчет мутно. Тут надо читать бой, а не понтоваться.',
  'signals': ['знаки', 'ритм', 'оберег'],
  'enemy_tags': ['spirit', 'raven', 'totem', 'wisp'],
  'elite_tags': ['elite_spirit', 'elite_totem', 'elite_bone'],
  'boss_tags': ['boss_khan', 'boss_ritualist', 'boss_chain'],
  'modifiers': {'combo_mult': 1.14, 'pair_mult': 1.08, 'enemy_hp_mult': 1.05, 'reward_mult': 1.08}},
 {'id': 'ash',
  'location': 'Пепельная лощина',
  'hint': 'Зола ещё тёплая. Жар дышит из-под копыта.',
  'slang': 'Тут всё тлеет. Если разжёг — не отпускай.',
  'signals': ['зола', 'угли', 'душный жар'],
  'enemy_tags': ['jackal', 'spirit', 'totem'],
  'elite_tags': ['elite_howler', 'elite_spirit', 'elite_totem'],
  'boss_tags': ['boss_pyre', 'boss_drought'],
  'modifiers': {'burn_mult': 1.18, 'fire_pair_mult': 1.1, 'enemy_attack_mult': 1.06, 'reward_mult': 1.04}},
 {'id': 'howls',
  'location': 'Волчья падь',
  'hint': 'Одиночки тут редко ходят. Если шум поднялся — полезут кучей.',
  'slang': 'Тут стая любит навалиться гуртом, не моргай.',
  'signals': ['следы стаи', 'рык', 'много лап'],
  'enemy_tags': ['wolf', 'jackal', 'raven'],
  'elite_tags': ['elite_wolf', 'elite_howler', 'elite_raven'],
  'boss_tags': ['boss_wolf', 'boss_chain'],
  'modifiers': {'group_count': 6, 'group_hp_mult': 1.14, 'enemy_attack_mult': 1.05, 'reward_mult': 1.06}},
 {'id': 'iron',
  'location': 'Железный перевал',
  'hint': 'Тут всё гремит и держит удар. Мягкой рукой делать нечего.',
  'slang': 'Перевал железный: кто не ломает, тот стучит вхолостую.',
  'signals': ['гул металла', 'скрежет', 'заклёпки'],
  'enemy_tags': ['totem', 'yak', 'scarab'],
  'elite_tags': ['elite_bull', 'elite_totem', 'elite_bone'],
  'boss_tags': ['boss_idol', 'boss_stonehide', 'boss_guard'],
  'modifiers': {'enemy_armor_mult': 1.18, 'shield_mult': 1.22, 'earth_pair_mult': 1.1, 'reward_mult': 1.08}},
 {'id': 'reeds',
  'location': 'Шёпотный камыш',
  'hint': 'Тут звук тонет, а движение вязнет. Кто умеет зажимать — разберётся.',
  'slang': 'Камыш шепчет тихо, но держит крепко.',
  'signals': ['камыш', 'вязкая вода', 'тихий шорох'],
  'enemy_tags': ['mireling', 'spirit', 'wisp'],
  'elite_tags': ['elite_mire', 'elite_spirit', 'elite_raven'],
  'boss_tags': ['boss_tidekeeper', 'boss_marsh'],
  'modifiers': {'hold_mult': 1.14, 'combo_mult': 1.08, 'enemy_attack_interval_mult': 1.04, 'burn_mult': 0.92}},
 {'id': 'gale',
  'location': 'Шквальный гребень',
  'hint': 'Сильный ветер любит тех, кто режет по направлению.',
  'slang': 'Тут ветер рулит, кривой рисунок сразу палится.',
  'signals': ['шквал', 'резкий порыв', 'срыв темпа'],
  'enemy_tags': ['raven', 'moth', 'spirit'],
  'elite_tags': ['elite_raven', 'elite_spirit'],
  'boss_tags': ['boss_wind', 'boss_mirror'],
  'modifiers': {'swipe_mult': 1.2, 'tap_mult': 0.9, 'air_pair_mult': 1.12, 'enemy_attack_interval_mult': 0.92}},
 {'id': 'dusk',
  'location': 'Сумеречный коридор',
  'hint': 'Свет тонкий, силуэты скачут. Тут хорошо читается точный удар.',
  'slang': 'Полутень любит точность: мазанул — сам виноват.',
  'signals': ['полутень', 'острый силуэт', 'тихий блеск'],
  'enemy_tags': ['wisp', 'raven', 'spirit'],
  'elite_tags': ['elite_raven', 'elite_bone', 'elite_spirit'],
  'boss_tags': ['boss_wolf', 'boss_ritualist'],
  'modifiers': {'tap_mult': 1.14, 'crit_mult': 1.14, 'enemy_attack_mult': 1.04}},
 {'id': 'shrine',
  'location': 'Треснувшее капище',
  'hint': 'Печати лопаются не сразу. Длинная связка тут читается лучше.',
  'slang': 'Капище любит тех, кто не рвёт рисунок на полпути.',
  'signals': ['трещины', 'печати', 'долгий рисунок'],
  'enemy_tags': ['totem', 'wisp', 'spirit'],
  'elite_tags': ['elite_totem', 'elite_bone', 'elite_rift'],
  'boss_tags': ['boss_guard', 'boss_ritualist', 'boss_chain'],
  'modifiers': {'combo_mult': 1.16, 'enemy_hp_mult': 1.08, 'reward_mult': 1.08}},
 {'id': 'mire',
  'location': 'Солончаковая топь',
  'hint': 'Ногу тут тянет вниз. Держи нажим, не суетись.',
  'slang': 'Тут вязко и зло. Кто терпит — тот и дожимает.',
  'signals': ['соль', 'липкая грязь', 'тягучесть'],
  'enemy_tags': ['mireling', 'yak', 'spirit'],
  'elite_tags': ['elite_mire', 'elite_bull', 'elite_rift'],
  'boss_tags': ['boss_void', 'boss_marsh', 'boss_tidekeeper'],
  'modifiers': {'hold_mult': 1.24, 'swipe_mult': 0.92, 'enemy_attack_interval_mult': 1.1, 'water_pair_mult': 1.08}},
 {'id': 'dust',
  'location': 'Пыльный прогон',
  'hint': 'В пыли всё решает первый плотный удар и быстрый дожим.',
  'slang': 'Поднял пыль — бей сразу, пока цель не очухалась.',
  'signals': ['пыль столбом', 'рывок', 'короткое окно'],
  'enemy_tags': ['jackal', 'wolf', 'scarab'],
  'elite_tags': ['elite_howler', 'elite_bull', 'elite_wolf'],
  'boss_tags': ['boss_wolf', 'boss_drought', 'boss_chain'],
  'modifiers': {'tap_mult': 1.16, 'swipe_mult': 1.06, 'enemy_attack_interval_mult': 0.95}},
 {'id': 'blacksky',
  'location': 'Чёрный кош',
  'hint': 'Место хитрое: одну и ту же манеру тут быстро читают.',
  'slang': 'Кош не любит тупой повтор. Миксуй, брат, иначе засмеют.',
  'signals': ['чёрный дым', 'ломаный ритм', 'странный отклик'],
  'enemy_tags': ['wisp', 'totem', 'raven', 'spirit'],
  'elite_tags': ['elite_bone', 'elite_rift', 'elite_raven'],
  'boss_tags': ['boss_chain', 'boss_mirror', 'boss_ritualist'],
  'modifiers': {'pair_mult': 1.1, 'enemy_hp_mult': 1.06, 'reward_mult': 1.1}}]

ENEMIES = [{'id': 'wolf',
  'name': 'Степной Волчара',
  'glyph': '/assets/enemies/wolf.svg',
  'base_hp': 16,
  'reward_mult': 1.0,
  'flavor': 'Шныряет рядом. Даёшь по клыкам и дальше по фарму.'},
 {'id': 'raven',
  'name': 'Чёрный Каркун',
  'glyph': '/assets/enemies/raven.svg',
  'base_hp': 14,
  'reward_mult': 1.05,
  'flavor': 'Орёт над головой и бесит с первого кадра.'},
 {'id': 'spirit',
  'name': 'Левый Дух',
  'glyph': '/assets/enemies/spirit.svg',
  'base_hp': 18,
  'reward_mult': 1.12,
  'flavor': 'Вылез не по делу. Сдувай его без церемоний.'},
 {'id': 'totem',
  'name': 'Кривой Тотем',
  'glyph': '/assets/enemies/totem.svg',
  'base_hp': 20,
  'reward_mult': 1.18,
  'flavor': 'Стоит криво, бьёт больно. Нормальная степная жесть.'},
 {'id': 'jackal',
  'name': 'Пыльный Шакал',
  'glyph': '/assets/enemies/jackal.svg',
  'base_hp': 15,
  'reward_mult': 1.08,
  'flavor': 'Мелкий, наглый и всегда лезет не в свой бой.'},
 {'id': 'wisp',
  'name': 'Шальной Огонёк',
  'glyph': '/assets/enemies/wisp.svg',
  'base_hp': 17,
  'reward_mult': 1.1,
  'flavor': 'Мерцает, юлит и пытается вынести мозг.'},
 {'id': 'moth',
  'name': 'Буревой Мотылёк',
  'glyph': '/assets/enemies/moth.svg',
  'base_hp': 13,
  'reward_mult': 1.07,
  'flavor': 'Крутится в воздухе и сбивает ритм.'},
 {'id': 'yak',
  'name': 'Каменный Як',
  'glyph': '/assets/enemies/yak.svg',
  'base_hp': 22,
  'reward_mult': 1.16,
  'flavor': 'Тяжёлый как курган. Лучше не встречать лбом.'},
 {'id': 'scarab',
  'name': 'Пустынный Скараба',
  'glyph': '/assets/enemies/scarab.svg',
  'base_hp': 16,
  'reward_mult': 1.09,
  'flavor': 'Скрипит панцирем и лезет под руку.'},
 {'id': 'mireling',
  'name': 'Топкий Ползун',
  'glyph': '/assets/enemies/mireling.svg',
  'base_hp': 19,
  'reward_mult': 1.13,
  'flavor': 'Тянет бой в грязь и липнет как беда.'}]

ELITES = [{'id': 'elite_wolf',
  'name': 'Элитный Волчара',
  'asset': '/assets/elites/elite_wolf.svg',
  'hp_mult': 4.4,
  'reward_mult': 3.4,
  'flavor': 'Вожак стаи, тут уже без суеты не вывезешь.'},
 {'id': 'elite_spirit',
  'name': 'Разломный Дух',
  'asset': '/assets/elites/elite_spirit.svg',
  'hp_mult': 4.8,
  'reward_mult': 3.8,
  'flavor': 'Туманная жесть с разлома, бьёт жёстко.'},
 {'id': 'elite_totem',
  'name': 'Древний Идол',
  'asset': '/assets/elites/elite_totem.svg',
  'hp_mult': 5.2,
  'reward_mult': 4.3,
  'flavor': 'Резной столб, но характер у него как у рейд-босса.'},
 {'id': 'elite_rift',
  'name': 'Разрыв Пустоты',
  'asset': '/assets/elites/elite_rift.svg',
  'hp_mult': 5.6,
  'reward_mult': 4.7,
  'flavor': 'Степь рядом с ним прям корёжит, будь начеку.'},
 {'id': 'elite_raven',
  'name': 'Штормовой Каркун',
  'asset': '/assets/elites/elite_raven.svg',
  'hp_mult': 4.6,
  'reward_mult': 3.7,
  'flavor': 'Летит как скандал: шумный и больной на голову.'},
 {'id': 'elite_bull',
  'name': 'Курганный Бык',
  'asset': '/assets/elites/elite_bull.svg',
  'hp_mult': 5.4,
  'reward_mult': 4.4,
  'flavor': 'Прёт в лоб и не собирается сворачивать.'},
 {'id': 'elite_bone',
  'name': 'Костяной Смотрящий',
  'asset': '/assets/elites/elite_bone.svg',
  'hp_mult': 5.1,
  'reward_mult': 4.2,
  'flavor': 'Стоит тихо, а потом ломает темп целиком.'},
 {'id': 'elite_mire',
  'name': 'Топкий Староста',
  'asset': '/assets/elites/elite_mire.svg',
  'hp_mult': 5.0,
  'reward_mult': 4.1,
  'flavor': 'Затягивает бой в липкую долгую возню.'},
 {'id': 'elite_howler',
  'name': 'Вой-пастух',
  'asset': '/assets/elites/elite_howler.svg',
  'hp_mult': 4.9,
  'reward_mult': 4.0,
  'flavor': 'Поднимает стаю одним криком.'}]

BOSSES = [{'id': 'boss_wolf',
  'name': 'Затменный Волчара',
  'asset': '/assets/bosses/boss_wolf.svg',
  'hp_mult': 7.4,
  'reward_mult': 8.6,
  'flavor': 'Ночной хозяин степи. Если вышел — будет мясо.',
  'mechanic': 'shadow',
  'mechanic_name': 'Теневая фаза',
  'mechanic_desc': 'Ушёл в тень — дави тапом. DPS мимо кассы.'},
 {'id': 'boss_idol',
  'name': 'Грозовой Идол',
  'asset': '/assets/bosses/boss_idol.svg',
  'hp_mult': 8.1,
  'reward_mult': 9.4,
  'flavor': 'Каменная махина, заряженная молнией по полной.',
  'mechanic': 'shield_hits',
  'mechanic_name': 'Щит',
  'mechanic_desc': 'Сначала режь щит свайпами через Землю. Потом уже наваливай.'},
 {'id': 'boss_guard',
  'name': 'Курганный Дед',
  'asset': '/assets/bosses/boss_guard.svg',
  'hp_mult': 8.8,
  'reward_mult': 10.3,
  'flavor': 'Поднялся с кургана и явно не рад гостям.',
  'mechanic': 'combo_gate',
  'mechanic_name': 'Печать',
  'mechanic_desc': 'Печать снимается тяжёлым свайпом вниз через Землю или длинным земным прокастом.'},
 {'id': 'boss_khan',
  'name': 'Костяной Хан',
  'asset': '/assets/bosses/boss_khan.svg',
  'hp_mult': 9.6,
  'reward_mult': 11.6,
  'flavor': 'Старый хан вернулся и хочет забрать весь лут.',
  'mechanic': 'rage_phase',
  'mechanic_name': 'Ярость',
  'mechanic_desc': 'Во второй фазе комбо и hold влетают заметно больнее. Не отпускай темп.'},
 {'id': 'boss_wind',
  'name': 'Хозяйка Бури',
  'asset': '/assets/bosses/boss_wind.svg',
  'hp_mult': 10.4,
  'reward_mult': 12.9,
  'flavor': 'С её бурей даже бывалые шаманы приседают.',
  'mechanic': 'swipe_gate',
  'mechanic_name': 'Буря',
  'mechanic_desc': 'Тап тут ватный. Вскрывай босса свайпами.'},
 {'id': 'boss_void',
  'name': 'Разломный Узел',
  'asset': '/assets/bosses/boss_void.svg',
  'hp_mult': 11.0,
  'reward_mult': 14.1,
  'flavor': 'Чистая пустотная жуть, тут без прокаста никак.',
  'mechanic': 'hold_gate',
  'mechanic_name': 'Узел',
  'mechanic_desc': 'Зажимай hold. Вода тут заходит лучше всего.'},
 {'id': 'boss_pyre',
  'name': 'Жаровня Кургана',
  'asset': '/assets/bosses/boss_pyre.svg',
  'hp_mult': 10.2,
  'reward_mult': 13.0,
  'flavor': 'Пылает так, будто всю степь хочет спалить.',
  'mechanic': 'burn_gate',
  'mechanic_name': 'Сухая шкура',
  'mechanic_desc': 'Обычный урон вязнет. Поджигай и раздувай горение.'},
 {'id': 'boss_stonehide',
  'name': 'Кремневый Хребет',
  'asset': '/assets/bosses/boss_stonehide.svg',
  'hp_mult': 10.8,
  'reward_mult': 13.5,
  'flavor': 'Хрустит камнем. Любит ловить тех, кто пришёл без Земли.',
  'mechanic': 'armor_gate',
  'mechanic_name': 'Каменный панцирь',
  'mechanic_desc': 'Пока не вскрыл броню, босс почти не чувствует ударов.'},
 {'id': 'boss_mirror',
  'name': 'Зеркальный Шквал',
  'asset': '/assets/bosses/boss_mirror.svg',
  'hp_mult': 10.6,
  'reward_mult': 13.7,
  'flavor': 'Любит читать одинаковые движения и отвечать в лицо.',
  'mechanic': 'mirror_swipe',
  'mechanic_name': 'Ломает ритм',
  'mechanic_desc': 'Один и тот же свайп подряд тухнет. Меняй направление.'},
 {'id': 'boss_tidekeeper',
  'name': 'Смотрящий Омут',
  'asset': '/assets/bosses/boss_tidekeeper.svg',
  'hp_mult': 10.9,
  'reward_mult': 13.9,
  'flavor': 'Тянет бой в глубину и любит тех, кто умеет держать поток.',
  'mechanic': 'hold_gate',
  'mechanic_name': 'Глубинный поток',
  'mechanic_desc': 'Короткие удары вязнут. Держи hold и вскрывай окно.'},
 {'id': 'boss_ritualist',
  'name': 'Пыльный Заклинатель',
  'asset': '/assets/bosses/boss_ritualist.svg',
  'hp_mult': 10.7,
  'reward_mult': 13.6,
  'flavor': 'Не прощает лобовой игры. Любит, когда шаман думает.',
  'mechanic': 'ritual_cycle',
  'mechanic_name': 'Фазы ритуала',
  'mechanic_desc': 'Босс меняет фазу по ходу боя. Подстраивай связку действий.'},
 {'id': 'boss_chain',
  'name': 'Пожиратель Связок',
  'asset': '/assets/bosses/boss_chain.svg',
  'hp_mult': 11.4,
  'reward_mult': 14.5,
  'flavor': 'Запоминает твои мувы и жрёт повторы.',
  'mechanic': 'chain_breaker',
  'mechanic_name': 'Жрёт повторы',
  'mechanic_desc': 'Не спамь один источник. Смешивай tap, swipe и hold.'},
 {'id': 'boss_drought',
  'name': 'Пастух Засухи',
  'asset': '/assets/bosses/boss_drought.svg',
  'hp_mult': 10.7,
  'reward_mult': 13.4,
  'flavor': 'Сушит воздух и заставляет спешить с жаром.',
  'mechanic': 'burn_gate',
  'mechanic_name': 'Сухой наст',
  'mechanic_desc': 'Пока цель не горит по-настоящему, обычный урон вязнет.'},
 {'id': 'boss_marsh',
  'name': 'Соляной Омут',
  'asset': '/assets/bosses/boss_marsh.svg',
  'hp_mult': 10.8,
  'reward_mult': 13.8,
  'flavor': 'Тянет в вязь и любит тех, кто держит нажим до конца.',
  'mechanic': 'hold_gate',
  'mechanic_name': 'Тягучий узел',
  'mechanic_desc': 'Короткие тычки тонут. Держи hold и вскрывай фазу.'},
 {'id': 'boss_howl',
  'name': 'Волчий Регент',
  'asset': '/assets/bosses/boss_howl.svg',
  'hp_mult': 10.5,
  'reward_mult': 13.3,
  'flavor': 'Стая слушает его с полувзгляда. Один промах — и навалятся всем кошем.',
  'mechanic': 'chain_breaker',
  'mechanic_name': 'Срыв привычки',
  'mechanic_desc': 'Повтор одного источника урона штрафуется. Миксуй темп.'}]

HEROES = [{'id': 'fire',
  'name': 'Шаман Огня',
  'title': 'жарит с руки',
  'asset': '/assets/heroes/hero_fire.png',
  'base_cost': 100,
  'base_dps': 12.0,
  'desc': 'Усиливает тап, поджигает и держит темп.',
  'growth': 1.19},
 {'id': 'water',
  'name': 'Шаман Воды',
  'title': 'льёт и держит',
  'asset': '/assets/heroes/hero_water.png',
  'base_cost': 100,
  'base_dps': 12.0,
  'desc': 'Усиливает hold, подлечивает и стабилизирует бой.',
  'growth': 1.19},
 {'id': 'earth',
  'name': 'Шаман Земли',
  'title': 'ломает жир',
  'asset': '/assets/heroes/hero_earth.png',
  'base_cost': 100,
  'base_dps': 12.0,
  'desc': 'Лучший по броне, щитам и тяжёлым целям.',
  'growth': 1.19},
 {'id': 'air',
  'name': 'Шаман Воздуха',
  'title': 'режет темп',
  'asset': '/assets/heroes/hero_air.png',
  'base_cost': 100,
  'base_dps': 12.0,
  'desc': 'Качает свайпы, ритм и длинные связки.',
  'growth': 1.19}]

RITUALS = [
    {
        "id": "embers",
        "name": "Ритуал Углей",
        "base_cost": 120,
        "cost_mult": 1.68,
        "desc": "+10% к тапу за уровень. Рука станет злее.",
    },
    {
        "id": "tide",
        "name": "Ритуал Прилива",
        "base_cost": 165,
        "cost_mult": 1.7,
        "desc": "+10% к золоту. Фарм идёт жирнее.",
    },
    {
        "id": "stone",
        "name": "Ритуал Камня",
        "base_cost": 240,
        "cost_mult": 1.72,
        "desc": "+1.0% к криту. Проки пойдут чаще.",
    },
    {
        "id": "storm",
        "name": "Ритуал Бури",
        "base_cost": 340,
        "cost_mult": 1.74,
        "desc": "+10% к DPS. Весь круг бьёт жёстче.",
    },
]

BREAKPOINTS = (10, 25, 50, 100)
HOLD_MIN_MS = 240
HOLD_MAX_MS = 2200
HOLD_BASE_TICKS = 4

HERO_MILESTONES = {
    "fire": {
        10: "Криты поджигают цель.",
        25: "Горение тикает сильнее.",
        50: "Тап и свайп получают доп. шанс крита.",
        100: "Поджог разгоняет весь огонь до inferno.",
    },
    "water": {
        10: "Удержание тапа начинает канал воды.",
        25: "Отпускание даёт всплеск урона.",
        50: "Удержание льёт по группе сильнее.",
        100: "Долгий канал даёт штормовой релиз.",
    },
    "earth": {
        10: "Тапы и тяжёлые приёмы сильнее крошат броню.",
        25: "Элитки и боссы получают больше урона.",
        50: "После пробоя брони цель мягче для дожима.",
        100: "Земля даёт тяжёлый shatter-эффект.",
    },
    "air": {
        10: "Свайпы становятся заметно сильнее.",
        25: "Комбо набираются быстрее.",
        50: "Воздушные связки сильнее по пачкам.",
        100: "Длинные комбо открывают жёсткое окно уязвимости.",
    },
}
